### PR TITLE
Skeleton chromies code

### PR DESCRIPTION
**Pull request by PapaSejd**
The skeleton code for chromies. Change the name when you feel like it. Also I did this on the browser so add it to the dme manually yourself.

Totally untested! That's also something you'll have to do.

#224

### CODE REVIEW

**Comment by PapaSejd** [comment]
added the display for it

**Comment by PapaSejd** [comment]
aight it compiles, good

**Comment by Orange-jpg** [comment]
God damn bro, adding chromies from lfieweb to this

**Comment by SireTurret2** [comment]
gonna need to rename it!

**Pull request merged**
